ALTER TABLE servers ADD COLUMN icon_url TEXT NOT NULL DEFAULT '';
ALTER TABLE servers ADD COLUMN banner_url TEXT NOT NULL DEFAULT '';
ALTER TABLE servers ADD COLUMN accent_color TEXT NOT NULL DEFAULT '';
ALTER TABLE servers ADD COLUMN traits_json TEXT NOT NULL DEFAULT '[]';
